import clsx from "clsx";
import { Provider } from "jotai";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/header/header";
import { QueryProvider } from "@/provider/query-provider";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          "relative antialiased bg-black min-h-screen bg-no-repeat",
          "has-[[data-admin]]:bg-gray-50",
          "has-[[data-admin]]:bg-(image:--bg-admin)",
          "has-[[data-home]]:bg-(image:--bg-home)",
          "has-[[data-theme]]:bg-(image:--bg-profile)"
        )}
      >
        <QueryProvider>
          <SessionProvider>
            <Provider>
              <Header />
              <div className="sm:pt-20 pt-17.5 min-h-screen relative">
                {children}
              </div>
              {modal}
            </Provider>
          </SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
